name: Build And Deploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: bank

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Cache do Gradle
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 18 (Corretto)
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'corretto'

      - name: Grant execute permission to Gradlew
        run: chmod +x gradlew

      # Build do Fat Jar
      - name: Build Ktor fat JAR
        run: ./gradlew clean buildFatJar

      # Salvar o caminho real do JAR
      - name: Find generated JAR
        id: jar
        run: |
          FILE=$(ls build/libs/*-all.jar | head -n 1)
          echo "jar_path=$FILE" >> $GITHUB_OUTPUT

      # Criar release com o JAR gerado
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "release-${{ github.run_number }}"
          name: "Build ${{ github.run_number }}"
          files: ${{ steps.jar.outputs.jar_path }}

      # Enviar para EC2
      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ${{ steps.jar.outputs.jar_path }}
          target: "/home/ubuntu/bank/"

      # Restart servi√ßo
      - name: Restart Ktor service on EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl stop bank-backend || true
            cd /home/ubuntu/bank
            rm -f *.jar
            sudo mv /home/ubuntu/bank/build/libs/pucBank-all.jar /home/ubuntu/bank/app.jar
            sudo systemctl start bank-backend
            sudo systemctl status bank-backend --no-pager